// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    var errorCount, removeError, submitBtn, throwError, valEl, validate;
    errorCount = null;
    valEl = $('.validate');
    submitBtn = valEl.parent().parent().find('input[type=submit]');
    valEl.on("blur", function() {
      var input;
      input = $(this);
      return validate(input);
    });
    validate = function(input) {
      var inputLen, inputVal, isInteger, validations;
      inputVal = input.val();
      inputLen = inputVal.length;
      validations = input.data();
      if (validations.notblank === true) {
        if (inputLen <= 0) {
          throwError("This field can't be blank", input);
        } else {
          removeError(input);
        }
      }
      if (validations.minchars > 0) {
        if (inputLen < validations.minchars) {
          throwError("You need at least 5 chars", input);
        } else {
          removeError(input);
        }
      }
      if (validations.isinteger === true) {
        isInteger = /^\d+$/;
        if (isInteger.test(inputVal) === false) {
          return throwError("Must be a whole number", input);
        } else {
          return removeError(input);
        }
      }
    };
    throwError = function(message, input) {
      if (!input.hasClass('has-error')) {
        errorCount += 1;
        input.addClass("has-error");
        return input.nextAll('.errorContainer').append(message);
      }
    };
    removeError = function(input) {
      if (input.hasClass('has-error')) {
        errorCount -= 1;
        input.removeClass("has-error");
        return input.nextAll('.errorContainer').empty();
      }
    };
    return submitBtn.on("click", function(e) {
      e.preventDefault();
      if (errorCount === 0) {
        return valEl.parent().parent().submit();
      }
    });
  });

}).call(this);
